### ISSUE TITLE
大佬能否加个插件的license？

### ISSUE THREAD

**Issue by kissnature** [Z-H-Sun/CS_CCME_Posts#10]
ElViS的插件似乎尚未包含在内~

用来处理IR之类的谱图。

若大佬能抽空加上，万分感谢~

**Comment by Z-H-Sun** [comment]
Hi,

I can't guarantee, but we can try if you are really in need of this. In such a case, your help is necessary.

The problem is that I don't know what the license file looks like. I think as long as we know that, we will probably be able to do the trick, whether or not the license is valid.

That being said, you can try applying for a trial version on the MRab official website

Remember to tick the ElViS plugin.

Once your trial is approved, please send that license file to me, and maybe I can find a way to make it work even after the 45-day trial period.

Let's do it if you think what I said above is OK to you.

**Comment by kissnature** [comment]
Many thanks for your help!

(ElViS_v1.3.lic is the one I want to use.)

Here is the trial license I just got.

I do need the plugin to analyze some IR data but definitely not in a hurry! 

I appreciate it a lot if you can give it a try when you get some free time!

**Comment by Z-H-Sun** [comment]
Solved. Please unshare the Google Drive link immediately to avoid undesired privacy leakage.

To do the trick, replace the contents of `ElViS_v1.3.txt` with the following, and then re-install the license file. Alternatively, put the file into the `licenses` subfolder of the installation path of M Nova. That is it.

```
<mlic version="1.0">
<licid>{0-0-0-0-0}</licid>
<type>single</type>
<hostid>0-0-0-0</hostid>
<vendor></vendor>
<purchaser>foss@ru-board</purchaser>
<product>ElViS</product>
<version>1.3</version>
<uuid>{d1956e14-b9ae-4b39-a507-a139a58688e3}</uuid>
<count>unlimited</count>
<issued>2000-01-01</issued>
<expires>never</expires>
<update>forever</update>
<sign>cnUtYm9hcmQ=</sign>
</mlic>
```

As you can see, the `licid` and `hostid` are 0-0-0-0, so it is definitely an invalid license file. But since you patched M Nova, it can trick the program and bypass the authentification.

In fact, if you desire to crack other plugins, what you really need to know is: a) `<product>` and b) `<uuid>`. Replacing these values above give you a dummy license file for that plugin.
