### ISSUE TITLE
Activation required when using Python version of Chem Script

### ISSUE THREAD

**Issue by GroundStateGecko** [Z-H-Sun/CS_CCME_Posts#15]
Hi Sun, really appreciate for sharing those programs. They have helped me for years. 

I've an issue that when I try to use Chem Script (Python 3.9), an activation requrest pop-up during the import. 

## Environment

Windows 10, newest update. 
Installed cos22.0_Crack.exe. All after-install patches green, including those about `C:\ProgramFiles\PerkinElmerInformatics\Chem Office2022\Chem Script\Lib\Chem Script220.dll`. 
All other Chem Office parts shows patched. 

## How to recreate the problem:

- Install the program with Chem Script and Python 3.9 x64.
- Patch the program.
- Go to start menu and find `Chem Script Demo 64-bit.lnk`
- Double click to run, press Enter twice to see this popup. I'm not allowed to go forward without filling registration:

![image](https://user-images.githubusercontent.com/82683392/225433676-6a880bdc-4107-440e-880a-f72928d87868.png)

Same activation requirement popup when importing Chem Script22 from my own python 3.9 environment.

## Other information
Note that the .Net x64 demo of Chem Script works find (below showing a successfully generated cdx file from `Chem Script Demo .Net 64-bit.lnk` demo). It's just the python version of Chem Script that doesn't work:

![image](https://user-images.githubusercontent.com/82683392/225435554-09f382dd-6859-46ab-b5d3-7164b8abfa59.png)

**Comment by Z-H-Sun** [comment]
Thank you for the detailed report and sorry for the delay. I personally never use Chem Script, so I had put this to the lowest priority on my TODO list. I was able to reproduce this issue, and this was indeed my mistake. However, <ins><i>this can be easily fixed, shown below</i></ins>, and I will incorporate this fix into the next version of the patch.

Long story short, this issue is because the Python version of Chem Script does not reference any of the `Chem ScriptXXX.dll`, but rather `_Chem Script22forPyXX.pyd` instead. But in my patch, only `exe` and `dll` files are patched, not including these `pyd` files. So (before I publish the next version of the patch), there is a simple workaround:

* Rename `<...>/Chem Office2022/Chem Script/Lib/_Chem Script22forPy39.pyd` into `.dll`
* Rerun the old patch `COS_Win_Patch.exe` (you can find it [here](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.15/COS_Win_Patch.exe))
  * You should be able to see this line:
  > ...\\Chem Script\\Lib\\_Chem Script22forPy39.dll
  >
  > Patched pattern [2d 04 17 0a 2b 02 `16` 0a 06 0b 07 2a] found at offset 0x7f0cea : Patched
* Rename `_Chem Script22forPy39.dll` back to `.pyd`
* OK.

Now you should be able to see something like this when running the Python demo for Chem Script:
![](https://user-images.githubusercontent.com/48094808/231611976-5bb9462d-3bf3-4fde-ab22-72dd358c550a.png)
