### ISSUE TITLE
如果采用“破解补丁”的方法，无法使用Excel里面的插件功能

### ISSUE THREAD

**Issue by wanzhiyu** [Z-H-Sun/CS_CCME_Posts#18]
若已经安装了未破解版或网传不完全破解版，则可单独下载使用[破解补丁](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.15r/COS_Win_Patch.exe)
我采用这个破解补丁破解了PerkinElmer ChemOffice Suite 2022 v22.2.0.3300，主体功能可以正常使用，但是Excel里面无法正常使用插件功能：
![图片](https://user-images.githubusercontent.com/18503895/233524115-4ca678af-ee9f-4401-8d2e-ed90e2e57859.png)

**Comment by wanzhiyu** [comment]
如果直接下载运行单文件版安装破解程序cos22.0_Crack.exe，又会出现word中双击chemdraw结构卡死的情况，不是不能跳转到chemdraw，而是跳转到chemdraw内不显示结构卡死无响应

**Comment by wanzhiyu** [comment]
> 

PerkinElmer ChemOffice Suite 2022 v22.0.0.22我也试过，同样的问题

**Comment by skipskipthree** [comment]
尝试了多次发现，excel插件只有32位可以顺利运行。安装时需要同时选择32位程序，好像是只有32位的才可以在excel的插件正常运行
![image](https://user-images.githubusercontent.com/33718851/233527250-36d49a4f-babc-41de-80cd-765bb4335887.png)

**Comment by Z-H-Sun** [comment]
> 尝试了多次发现，excel插件只有32位可以顺利运行。安装时需要同时选择32位程序，好像是只有32位的才可以在excel的插件正常运行

This is because you installed the 32-bit version of Excel. ***The 64-bit plugin only works for 64-bit Excel, and the 32-bit plugin only works for 32-bit Excel.***

Quite straightforward, huh? This is evidenced by the fact that even the "New ChemOffice Worksheet" bottom is grayed out in your first picture, indicating that this plugin (64-bit) is not compatible with your Excel (32-bit).

> 如果直接下载运行单文件版安装破解程序cos22.0_Crack.exe，又会出现word中双击chemdraw结构卡死的情况，不是不能跳转到chemdraw，而是跳转到chemdraw内不显示结构卡死无响应

Never met this problem since ChemDraw 18. Likely still due to the incompatibility between your Word (32-bit) and the 64-bit ChemDraw, or because something got wrong with your Windows Defender (or similar antivirus service).

**Comment by wanzhiyu** [comment]
> 

对于我来说，我想可能并不是office套件的问题，我的word和excel都是64位版本（Office 365，正式版、非预览版）：
![图片](https://user-images.githubusercontent.com/18503895/233813682-492eee82-7a7f-4836-9103-8a3036b05378.png)

![图片](https://user-images.githubusercontent.com/18503895/233813670-df1c7f91-d80f-4f04-8f25-b05a30d897b2.png)

不过有一点值得说明的是，我在安装ChemOffice的时候，同时选择安装了64位和32位的版本，也就是说，我把安装向导中的所有选项都勾选了，请问这个是否会影响“单独下载使用[破解补丁](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.15r/COS_Win_Patch.exe)”的正常运行？

**Comment by wanzhiyu** [comment]
> 单独下载使用[破解补丁](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.15r/COS_Win_Patch.exe)

我的主要期望仍然是使得“单独下载使用[破解补丁](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.15r/COS_Win_Patch.exe)”正常运行excel插件，但是现在并不成功，是否“单独下载使用[破解补丁](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.15r/COS_Win_Patch.exe)”无法实现excel插件的正常运行？

**Comment by wanzhiyu** [comment]
> 

我和[skipskipthree](https://github.com/skipskipthree)的情况是不一样的，请您暂时忽略掉他提供的信息，我和他遇到的问题不相同且没有关联。

**Comment by Z-H-Sun** [comment]
> 我把安装向导中的所有选项都勾选了，请问这个是否会影响“单独下载使用破解补丁”的正常运行？

This is unlikely. They are processed separately.

> 我和skipskipthree的情况是不一样的，请您暂时忽略掉他提供的信息，我和他遇到的问题不相同且没有关联。

I agree that his problem is different than yours. Let's troubleshoot your problem then.

> This is evidenced by the fact that even the "New ChemOffice Worksheet" bottom is grayed out in your first picture.

This alone, i.e., whether the button is enabled, is not enough to tell whether the patch is successful. So I need more information.

Could you please click the "Options" button, and choose the menu item "Activate ChemDraw" like in (a) below and tell me which case among (b) to (d) you see?

![](https://user-images.githubusercontent.com/48094808/233821033-269c8d7a-b661-4100-a773-413c9feeb729.png)

Since you successfully patched other applications (you can run ChemDraw/Chem3D right?), I don't think you will see Case (b).

I think it is most likely that you will see Case (c), where the serial number is empty, which means the patch process itself has not been successful. It is likely that the time you ran the patch, the relevant DLL file was in use and could not be modified by the patch. Now, make sure you quit all Excel-related processes (or restart your computer to be sure), and then rerun the patch. Especially pay attention to this file, `CambridgeSoft.ChemOffice.ChemDrawExcel.LibChemDrawWrapper.dll`, framed in the picture below:

![](https://user-images.githubusercontent.com/48094808/233821229-11863e88-8919-44bc-bbef-43a281354b23.png)

If the patch is successful, it should say "Patched" at the end, and if the version you patch is 22.0.0.22, the patch location should be 0x2cf636 like shown in the picture (a) above. Then the plugin should be able to function immediately. If you see red texts like in (b), it means the file is in use, and the patch is unable to make the necessary modification. If this is the case, then it is not a problem of the patch- it has not even had the chance to do its job yet.

**Comment by wanzhiyu** [comment]
> Could you please click the "Options" button, and choose the menu item "Activate ChemDraw" like in (a) below and tell me which case among (b) to (d) you see?

我用的是最新版本的破解补丁，不管是excel里面，还是Chemdraw里面，都没有看到序列号，都是Case (c)
![图片](https://user-images.githubusercontent.com/18503895/235571884-0f2c3edd-df51-4b0f-a334-2e65e53b76d6.png)
![图片](https://user-images.githubusercontent.com/18503895/235571897-c5149002-4b32-4584-952d-2751f07b08e5.png)
![图片](https://user-images.githubusercontent.com/18503895/235571915-a7704750-1f94-473c-81d8-97b3580eba38.png)

我尝试了多次破解补丁，也没有遇到fail的情况，如下日志所示，所以不清楚到底哪里出现了问题，请问是否是我的版本高了一点（22.2）导致的？：
`
You have:
  32-bit ChemOffice [PerkinElmer ChemOffice Suite 22.2.0, Version 22.2] installed at
    C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\
  64-bit ChemOffice [PerkinElmer ChemOffice Suite 22.2.0 x64, Version 22.2] installed at
    C:\Program Files\PerkinElmerInformatics\ChemOffice\

Is the information correct? [Y/N] (Press `Y' or wait for 10 seconds to confirm; or press `N' within 10 seconds to decline and then enter the information manually) Y

Do you wish to [P]atch, [R]estore, or be [A]sked to decide for each file? (Press P, R, or A; or wait for 10 seconds to start with the `Patch' mode as the default choice) P

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\Common\DLLs\FlxComm.dll
Found .dll file : Renamed to .bak file.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\Common\DLLs\FlxCore.dll
Found .dll file : Renamed to .bak file.

C:\Program Files\PerkinElmerInformatics\ChemOffice\Common\DLLs\FlxComm64.dll
Found .dll file : Renamed to .bak file.

C:\Program Files\PerkinElmerInformatics\ChemOffice\Common\DLLs\FlxCore64.dll
Found .dll file : Renamed to .bak file.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\Common\DLLs\MolServer.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x57413e : Patched.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\Common\DLLs\CSMol.ocx
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x4ca7fe : Patched.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\Common\DLLs\CSCombi.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x3bdf22 : Patched.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\Common\COEA\ActivationHelper.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x61d72 : Patched.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\ChemFinder\ChemFinderForOffice.exe
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x2e282e : Patched.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\ChemFinder\ChemFinder.exe
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x2da1fe : Patched.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\ChemDraw for Excel\CambridgeSoft.ChemOffice.ChemDrawExcel.LibChemDrawWrapper.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x29ceee : Patched.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\ChemDraw\ChemDrawCtl.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x7d8d82 : Patched.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\ChemDraw\ChemDrawBase.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x681a8a : Patched.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\Chem3D\Chem3DCtl.OCX
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x2c5712 : Patched.

C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice\Chem3D\Chem3D.exe
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x6edab2 : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\Common\DLLs\MolServer.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x60759a : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\Common\DLLs\CSMol.ocx
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x537366 : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\Common\DLLs\CSCombi.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x40868e : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\Common\COEA\ActivationHelper.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x6931a : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\ChemScript\Lib\_ChemScriptForPy39.pyd
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x80e052 : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\ChemScript\Lib\_ChemScriptForPy310.pyd
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x80e042 : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\ChemScript\Lib\ChemScript.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x5be89a : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\ChemFinder\ChemFinderForOffice.exe
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x3193e2 : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\ChemDraw for Excel\CambridgeSoft.ChemOffice.ChemDrawExcel.LibChemDrawWrapper.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x2da672 : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\ChemDraw\ChemDrawCtl.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x7ba43e : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\ChemDraw\ChemDrawBase.dll
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x76ec1a : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\Chem3D\Chem3DCtl.ocx
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x32ecb6 : Patched.

C:\Program Files\PerkinElmerInformatics\ChemOffice\Chem3D\Chem3D.exe
Pattern to be patched [2d 04 17 0a 2b 02 16 0a 06 0b 07 2a] found at offset 0x7dac3a : Patched.

Among 28 activation-related files, 28 were patched, 0 were restored, 0 failed, and 0 were ignored.

Registry entries modified. END OF PATCH.
Optional: In the following lines, please input arbitrary info (or leave blank), and enjoy using ChemOffice Crack!
  User Name:    _______________`

**Comment by wanzhiyu** [comment]
我把版本该到了22.0，并且只安装了64位，似乎一切正常了。
![图片](https://user-images.githubusercontent.com/18503895/235574558-a32c073c-412a-4ec3-afee-76de32f370b3.png)
![图片](https://user-images.githubusercontent.com/18503895/235574568-ea4a8204-8235-4b22-9d3e-70319e97f47c.png)
![图片](https://user-images.githubusercontent.com/18503895/235574596-5129fc52-5bd6-42bb-aed5-7ef0a02b204f.png)

**Comment by Z-H-Sun** [comment]
I just tested Chem Office ver 22.2. Indeed, the current patch fail to work. To be clear, the patch does NOT work AT ALL for that latest version, and ChemDraw will not even run. The reason why you can still run ChemDraw is because you installed some cracked version, so it is this cracked version that works rather than the patch.

The cracked version is equivalent to the effect of [this deprecated patch](https://github.com/Z-H-Sun/CS_CCME_Posts/blob/hidden/cos/cos20.md#windows-下的替代破解法) and is known unable to work for ChemDrawExcel. For more information, read [this article](https://github.com/Z-H-Sun/CS_CCME_Posts/blob/hidden/cos/cow3.md) (and its referenced articles).

Now that we know where the problem is, I think I will work on it soon. I will not post any update in this thread anymore, because there has been so much irrelevant information that can be really misleading (for example, you used a cracked version, and Skipskipthree posted some totally irrelevant questions). Instead, I have opened a new issue (#20). So please check any updates there.

**Comment by wanzhiyu** [comment]
> Now that we know where the problem is, I think I will work on it soon.

Thank you for your great work!

**Comment by Z-H-Sun** [comment]
You can now try updating your ChemOffice to 22.2 and using [this nightly build of the latest patch](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.16/COS_Win_Patch.exe).

**Comment by wanzhiyu** [comment]
> You can now try updating your ChemOffice to 22.2 and using [this nightly build of the latest patch](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.16/COS_Win_Patch.exe).

已解决，谢谢
