### ISSUE TITLE
ChemDraw 19 on MAC

### ISSUE THREAD

**Issue by a-abdoman** [Z-H-Sun/CS_CCME_Posts#2]
I downloaded the ChemDrawBase that you provided.
After I replaced the original one from the official ChemDraw19, I run the chemdraw and got an error message: the package was damaged, and can't be opened. 
After I change back the ChemDrawBase, I can run the ChemDraw, but with license requirement.
My MBP: Catalina 10.15.3
Would you please give some suggestions?
PS: I also have problem with chemdraw16. The program is freezing, when I try to save an existing chemdraw file (edit).
The solution does not works for me. http://informatics.perkinelmer.com/Support/KnowledgeBase/details/Default?TechNote=3529

**Comment by a-abdoman** [comment]
It the the problem of signature of the crack file.
sudo codesign --force --deep --sign - path_to_Chem Draw Base solve the problem.

Sorry for this comment. It's my problem.

**Comment by Z-H-Sun** [comment]
> It the the problem of signature of the crack file.
> sudo codesign --force --deep --sign - path_to_Chem Draw Base solve the problem.
> 
> Sorry for this comment. It's my problem.

@a-abdoman Yes, this is caused by the annoying Mac OS gatekeeper. I intend to write a post recently on how to bypass this verification step when patching packages on Mac OS.

Also, I will publish a complete cr-a-ck for ChmDrw_for_Mac recently, which will definitely be more convenient than that "infinite trial" one. Please keep an eye on my posts.
