### ISSUE TITLE
提问及添加新软件请求

### ISSUE THREAD

**Issue by ScienceZone** [Z-H-Sun/CS_CCME_Posts#21]
大佬你好，请问“公众号”是什么？微信公众号吗？另外常用的作图软件Origin能不能支持一下？谢谢！

**Comment by Z-H-Sun** [comment]
> 大佬你好，请问“公众号”是什么？微信公众号吗？

Some articles were initially published on a Weixin Official Account of mine, but in early 2019, they were soon reported due to copyright violation by a notorious software agent dealer company, 思杰马克丁. So after that, I no longer post related stuff there, and I archived these old articles and began to update new articles here.

> 另外常用的作图软件Origin能不能支持一下？谢谢！

I am sorry, but this is not on my list.
