### ISSUE TITLE
Issue Accessing StereoFit Plugin

### ISSUE THREAD

**Issue by HollyGolightly27** [Z-H-Sun/CS_CCME_Posts#33]
Im using newest version of Mestrenova (15.0.1.-35756) on MacOS. I want to use the Stereofit plugin, however it does not appear in my software. I have double checked the license folder and the file is present. It also doesn't appear on the plug in menu so Im not sure what the issue is. If anyone knows a fix to get it so work I would appreciate it. 

Additionally, ElVis does not seem to work properly so I suspect some kind of issue is going on.

<img width="905" alt="1" src="https://github.com/user-attachments/assets/c17c6b52-520b-4004-940c-7155813504bf">
<img width="702" alt="2" src="https://github.com/user-attachments/assets/aa321346-e675-45a0-8e13-6589d0168c1c">

**Comment by Z-H-Sun** [comment]
This issue is totally irrelevant of the patcher.

As a user of the software, please carefully read its documentation before you would like to make use of its new feature.

For example, to use the MNova StereoFitter plugin, as clearly stated in [the official website here](https://mestrelab.com/software/mnova-software/mnova-stereofitter/), you need to install the plugin separately. For Mac OS users, [download the `zip` archive here](https://mestrelab.com/downloads/mnova/stereofitter/Mnova-StereoFitter-1.1.6.14588-mac.zip), extract its content, and drag the `xml` file to MNova to install the plugin. Then you will be able to use it.

As for ElViS, you didn't provide a clear description of the issue, but I'm guessing that you somehow were unable to load a spectrum file into MNova. Again, I recommend you read [its user manual](https://mestrelab.com/pdf/manuals/Mnova-ElViS-User-Manual.pdf) carefully. My suggestion is that you can convert your spectrum file into csv or txt file, which makes sure MNova can read the format. Especially, you should explicitly tell MNova that you are loading a spectrum file, by go to `File -> Open`, and select the `ElViS CSV` file type. Strictly following the user manual will allow you to use this new function without any problem, as I can testify on my side.
