### ISSUE TITLE
同一局域网内多台机器使用有弹窗提示，怎么破？

### ISSUE THREAD

**Issue by zhl82** [Z-H-Sun/CS_CCME_Posts#5]
同一局域网内多台机器使用有弹窗提示，怎么破？

**Comment by Z-H-Sun** [comment]
Seems to be the only known issue with this method, which is due to the limitations of the sequence number itself.

I will try alternative methods this weekend if I have time, but I can’t guarantee it will work.

**Comment by zhl82** [comment]
> Seems to be the only known issue with this method, which is due to the limitations of the sequence number itself. I will try alternative methods this weekend if I have time, but I can’t guarantee it will work.
> […](#)
> On Apr 6, 2021, at 01:36, zhl82 ***@***.***> wrote: ﻿ 同一局域网内多台机器使用有弹窗提示，怎么破？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks you very much, your works is already perfect!

**Comment by Z-H-Sun** [comment]
Could you please try this out: https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.12/COS_Win_Patch.Deprecated.exe

And tell me if you still have pop-up message. If the message persists, try using the old tool to "restore," and then see if it is fixed.

**Comment by Z-H-Sun** [comment]
To avoid misunderstanding, I am pasting the statement in the tool here as well:

> Note: Use this tool only when you want to activate multiple Chem Office users in your local network, as this crack method is flawed (e.g. Chem 3D hotlink cannot work properly in Chem Draw). Otherwise, try the other better crack tool here: https://bit.ly/3dHDGqJ.

i.e. the old crack tool

**Comment by zhl82** [comment]
I'm trying the new patch, so far no pop-up message appears.

**Comment by giveforceyes** [comment]
#2020 版，在win系统上，我测试了下，发现点问题，excel2016 插入不了化学图片，用chem draw2019可以

[https://cdn.jsdelivr.net/gh/giveforceyes/ImageYes@main/winmacyes/2020%E4%B8%8D%E5%87%BA%E5%9B%BE%E7%89%87%20%E6%8F%90%E7%A4%BA%E6%BF%80%E6%B4%BB%E6%8E%88%E6%9D%83%E4%B8%8D%E5%A4%9F%E9%AB%98.png](url)
[https://cdn.jsdelivr.net/gh/giveforceyes/ImageYes@main/winmacyes/20191.png](url)

**Comment by Z-H-Sun** [comment]
Which patch are you using? If you use the patch specially designed for local network users, as I mentioned here, [Windows下的替代破解方法](https://github.com/Z-H-Sun/CS_CCME_Posts/blob/hidden/cos/cos20.md#windows-%E4%B8%8B%E7%9A%84%E6%9B%BF%E4%BB%A3%E7%A0%B4%E8%A7%A3%E6%B3%95), it is a known issue that you CANNOT use Chem Draw for excel, and I explained the reason [here](https://github.com/Z-H-Sun/CS_CCME_Posts/blob/hidden/cos/cow.md#%E7%A0%B4%E8%A7%A3%E8%A1%A5%E4%B8%81vs%E6%9C%AC%E6%96%B9%E6%B3%95). Please read the documents.

If there is no other Chem Draw users in the local network, or you are not connected in a local network using an Ethernet cable, don’t use that patch. Use the other one instead

**Comment by giveforceyes** [comment]
好的，谢谢，因为我是在vm上测试，安装的是懒人版的一键安装，有点奇怪，2020软件是可以开启使用，就是excel插件使用有限制，同个环境测试了懒人版的2019，excel插件可以使用
---原始邮件---
***@***.***&gt;
发送时间:2021年5月4日 星期二 上午0:35
***@***.***&gt;
***@***.******@***.***&gt;
主题:Re: [Z-H-Sun/CS_CCME_Posts] 同一局域网内多台机器使用有弹窗提示，怎么破？ (#5)

**Comment by Z-H-Sun** [comment]
Weird. Mine is fine.

Could you please:
1. Open a new issue: Your topic is irrelavant of this thread, which might be misleading for others.
2. In your Excel Chem Draw 20 bar, click options -> activate chem draw for excel, and see what kind of window will pop up. If you are using the correct patch, you should see something like this; otherwise, a different window will pop up.

![17 22 43 463](https://user-images.githubusercontent.com/48094808/116935921-145fd100-ac35-11eb-87df-35eb5a00baba.png)

3. Try running the patch again ([download here](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.12/COS_Win_Patch.exe)), and see if any error message pop up (Note especially the last line which reads, "among xx files, xx patched, xx restored, xx failed, and xx ignored.") Ideally, all prompts should be green-colored.
4. Please attach any related screenshot.
