### ISSUE TITLE
Mestrenova & Chemdraw 能在 MacOS 12 上使用了嗎？

### ISSUE THREAD

**Issue by scout1256** [Z-H-Sun/CS_CCME_Posts#7]
首先非常感謝大佬在這塊領域的付出:) 
死忠粉絲 敬上

**Comment by Z-H-Sun** [comment]
Sorry, but I currently do not have a test environment. Nevertheless, could you please state more specifically what your issue is for Mac12?

**Comment by scout1256** [comment]
well, I haven't test it either.
I'll report here if it works on MacOS 12 :))

**Comment by Z-H-Sun** [comment]
Well, I don’t see any chance that it won’t work. For macOS 11, the issue was with the digital signature, but that was an easy fix. Let’s be optimistic for the moment. I am closing the issue for now but any follow up is welcome. Please fill free to reopen this issue anytime you find an issue with OS12. Thanks

**Comment by Z-H-Sun** [comment]
@scout1256 FYI: tested by other users.
![image](https://user-images.githubusercontent.com/48094808/176008726-da7a86ba-3f66-4707-807c-701ae7f38cb8.png)
