### ISSUE TITLE
MRN Windows

### ISSUE THREAD

**Issue by xgsdhm** [Z-H-Sun/CS_CCME_Posts#8]
Hello, AFTER I run the MestReNovaCrack patch on the Window computer, it shows an error and cannot be cracked. I would like to ask your method. The version I installed is "mestrenova-12.0.4-22023_x64". The error code is as follows:

Processing D:\MNN\MestReNova.exe...
This file might have already been patched [Press Y' to override]. Found pattern, JNZ -> JMP: 75 .. .* 0B 00 00 80 .* 0B 00 00 80 Error occurred: #<Errno::EBADF: Bad file descriptor - D:\MNN\MestReNova.exe> ["MestReNovaCrack.rb:34:in seek'", "MestReNovaCrack.rb:34:in patch'", "MestReNovaCrack.rb:19:in loop'", "MestReNovaCrack.rb:19:in patch'", "MestReNovaCrack.rb:103", "MestReNovaCrack.rb:101:in each'", "MestReNovaCrack.rb:101"]

Releasing .LIC files in D:\MNN\licenses...
All .LIC files have been created.

**Comment by Z-H-Sun** [comment]
Hi,

This means the handle to the file is somehow forced to be closed, before the program can proceed to patch the file. According to the log you provide, it seems the program is granted proper read & write permissions. Given that, the only possibility I can think of is the interference from antivirus software, which stubbornly tries to prevent the content of `MestReNova.exe` from being modified. It should not be a problem of the patch, because I just tried patching the same version of MestReNova (12.0.4-22023_x64) on my PC without any problem.

That being said, there are two workarounds; you can choose either one as you like:

1) I patched the `MestReNova.exe` of the same version for you. If you trust me, you can [download this patched exe file here](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.01/MestReNova.exe), and then replace `D:\MNN\MestReNova.exe` on your PC with it. That is it.

2) Otherwise, if you very much like to know what is the reason behind this error message, there are several things you can try, but currently I cannot guarantee a fix before more information is available, and we can continue discussing this topic in this thread. You can: close all antivirus software; or, try patching the MestReNova on other computers, see if it works, and copy those files to your computer.

**Comment by xgsdhm** [comment]
I am so excited.  I am so happy to receive your reply.  I have read your reply, and this is really a good method, because the computer is not with me now, I need to wait until tomorrow to operate on the computer.  We will keep in touch and reply to you after operation on the computer tomorrow.  Thank you so much for your help.

**Comment by Z-H-Sun** [comment]
You are most welcome
